set(_CATKIN_CURRENT_PACKAGE "ee_command")
set(ee_command_VERSION "0.0.0")
set(ee_command_MAINTAINER "liu <liu@todo.todo>")
set(ee_command_PACKAGE_FORMAT "2")
set(ee_command_BUILD_DEPENDS "actionlib" "actionlib_msgs" "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(ee_command_BUILD_EXPORT_DEPENDS "actionlib" "actionlib_msgs" "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(ee_command_BUILDTOOL_DEPENDS "catkin")
set(ee_command_BUILDTOOL_EXPORT_DEPENDS )
set(ee_command_EXEC_DEPENDS "actionlib" "actionlib_msgs" "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(ee_command_RUN_DEPENDS "actionlib" "actionlib_msgs" "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(ee_command_TEST_DEPENDS )
set(ee_command_DOC_DEPENDS )
set(ee_command_URL_WEBSITE "")
set(ee_command_URL_BUGTRACKER "")
set(ee_command_URL_REPOSITORY "")
set(ee_command_DEPRECATED "")