set(_CATKIN_CURRENT_PACKAGE "hiro_panda_ik")
set(hiro_panda_ik_VERSION "0.0.1")
set(hiro_panda_ik_MAINTAINER "Matthew Strong <mast4878@colorado.edu>")
set(hiro_panda_ik_PACKAGE_FORMAT "2")
set(hiro_panda_ik_BUILD_DEPENDS "kdl_parser" "roscpp" "rospy" "sensor_msgs" "std_msgs" "franka_control" "controller_interface" "dynamic_reconfigure" "franka_hw" "geometry_msgs" "hardware_interface" "libfranka" "pluginlib" "realtime_tools" "effort_controllers" "controller_manager")
set(hiro_panda_ik_BUILD_EXPORT_DEPENDS "kdl_parser" "roscpp" "rospy" "sensor_msgs" "std_msgs" "franka_control" "controller_interface" "dynamic_reconfigure" "franka_hw" "geometry_msgs" "hardware_interface" "libfranka" "pluginlib" "realtime_tools" "effort_controllers" "controller_manager")
set(hiro_panda_ik_BUILDTOOL_DEPENDS "catkin")
set(hiro_panda_ik_BUILDTOOL_EXPORT_DEPENDS )
set(hiro_panda_ik_EXEC_DEPENDS "kdl_parser" "roscpp" "rospy" "sensor_msgs" "std_msgs" "joint_state_publisher" "robot_state_publisher" "xacro" "kdl_parser" "joint_trajectory_controller" "joint_state_publisher" "franka_control" "message_runtime" "controller_interface" "dynamic_reconfigure" "franka_hw" "geometry_msgs" "hardware_interface" "libfranka" "pluginlib" "realtime_tools" "effort_controllers" "controller_manager")
set(hiro_panda_ik_RUN_DEPENDS "kdl_parser" "roscpp" "rospy" "sensor_msgs" "std_msgs" "joint_state_publisher" "robot_state_publisher" "xacro" "joint_trajectory_controller" "franka_control" "message_runtime" "controller_interface" "dynamic_reconfigure" "franka_hw" "geometry_msgs" "hardware_interface" "libfranka" "pluginlib" "realtime_tools" "effort_controllers" "controller_manager")
set(hiro_panda_ik_TEST_DEPENDS )
set(hiro_panda_ik_DOC_DEPENDS )
set(hiro_panda_ik_URL_WEBSITE "")
set(hiro_panda_ik_URL_BUGTRACKER "")
set(hiro_panda_ik_URL_REPOSITORY "https://github.com/peasant98/hiro_panda_ik")
set(hiro_panda_ik_DEPRECATED "")