set(_CATKIN_CURRENT_PACKAGE "panda_erg")
set(panda_erg_VERSION "0.0.0")
set(panda_erg_MAINTAINER "Kelly Merckaert <kelly.merckaert@vub.be>")
set(panda_erg_PACKAGE_FORMAT "1")
set(panda_erg_BUILD_DEPENDS "kdl_parser")
set(panda_erg_BUILD_EXPORT_DEPENDS "panda_description" "panda_control" "roscpp" "kdl_parser")
set(panda_erg_BUILDTOOL_DEPENDS "catkin")
set(panda_erg_BUILDTOOL_EXPORT_DEPENDS )
set(panda_erg_EXEC_DEPENDS "panda_description" "panda_control" "roscpp" "kdl_parser")
set(panda_erg_RUN_DEPENDS "panda_description" "panda_control" "roscpp" "kdl_parser")
set(panda_erg_TEST_DEPENDS )
set(panda_erg_DOC_DEPENDS )
set(panda_erg_URL_WEBSITE "")
set(panda_erg_URL_BUGTRACKER "")
set(panda_erg_URL_REPOSITORY "")
set(panda_erg_DEPRECATED "")