set(_CATKIN_CURRENT_PACKAGE "arm_training")
set(arm_training_VERSION "0.0.0")
set(arm_training_MAINTAINER "liu <liu@todo.todo>")
set(arm_training_PACKAGE_FORMAT "2")
set(arm_training_BUILD_DEPENDS "rospy")
set(arm_training_BUILD_EXPORT_DEPENDS "rospy")
set(arm_training_BUILDTOOL_DEPENDS "catkin")
set(arm_training_BUILDTOOL_EXPORT_DEPENDS )
set(arm_training_EXEC_DEPENDS "rospy")
set(arm_training_RUN_DEPENDS "rospy")
set(arm_training_TEST_DEPENDS )
set(arm_training_DOC_DEPENDS )
set(arm_training_URL_WEBSITE "")
set(arm_training_URL_BUGTRACKER "")
set(arm_training_URL_REPOSITORY "")
set(arm_training_DEPRECATED "")