(cl:defpackage action_controller-msg
  (:use )
  (:export
   "<MULTIDOFFOLLOWJOINTTRAJECTORYACTION>"
   "MULTIDOFFOLLOWJOINTTRAJECTORYACTION"
   "<MULTIDOFFOLLOWJOINTTRAJECTORYACTIONFEEDBACK>"
   "MULTIDOFFOLLOWJOINTTRAJECTORYACTIONFEEDBACK"
   "<MULTIDOFFOLLOWJOINTTRAJECTORYACTIONGOAL>"
   "MULTIDOFFOLLOWJOINTTRAJECTORYACTIONGOAL"
   "<MULTIDOFFOLLOWJOINTTRAJECTORYACTIONRESULT>"
   "MULTIDOFFOLLOWJOINTTRAJECTORYACTIONRESULT"
   "<MULTIDOFFOLLOWJOINTTRAJECTORYFEEDBACK>"
   "MULTIDOFFOLLOWJOINTTRAJECTORYFEEDBACK"
   "<MULTIDOFFOLLOWJOINTTRAJECTORYGOAL>"
   "MULTIDOFFOLLOWJOINTTRAJECTORYGOAL"
   "<MULTIDOFFOLLOWJOINTTRAJECTORYRESULT>"
   "MULTIDOFFOLLOWJOINTTRAJECTORYRESULT"
  ))

