set(_CATKIN_CURRENT_PACKAGE "panda_gazebo")
set(panda_gazebo_VERSION "0.0.0")
set(panda_gazebo_MAINTAINER "liu <yuanl0517@gmail.com>")
set(panda_gazebo_PACKAGE_FORMAT "1")
set(panda_gazebo_BUILD_DEPENDS )
set(panda_gazebo_BUILD_EXPORT_DEPENDS "gazebo_ros" "panda_description" "xacro" "gazebo_plugins" "gazebo_ros_control" "panda_control" "hiro_panda_ik" "ee_command" "arm_training" "panda_erg")
set(panda_gazebo_BUILDTOOL_DEPENDS "catkin")
set(panda_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(panda_gazebo_EXEC_DEPENDS "gazebo_ros" "panda_description" "xacro" "gazebo_plugins" "gazebo_ros_control" "panda_control" "hiro_panda_ik" "ee_command" "arm_training" "panda_erg")
set(panda_gazebo_RUN_DEPENDS "gazebo_ros" "panda_description" "xacro" "gazebo_plugins" "gazebo_ros_control" "panda_control" "hiro_panda_ik" "ee_command" "arm_training" "panda_erg")
set(panda_gazebo_TEST_DEPENDS )
set(panda_gazebo_DOC_DEPENDS )
set(panda_gazebo_URL_WEBSITE "")
set(panda_gazebo_URL_BUGTRACKER "")
set(panda_gazebo_URL_REPOSITORY "")
set(panda_gazebo_DEPRECATED "")