set(_CATKIN_CURRENT_PACKAGE "merge")
set(merge_VERSION "0.0.0")
set(merge_MAINTAINER "liu <liu@todo.todo>")
set(merge_PACKAGE_FORMAT "2")
set(merge_BUILD_DEPENDS "hector_quadrotor_demo" "hector_quadrotor_gazebo" "panda_description" "panda_gazebo" "panda_control")
set(merge_BUILD_EXPORT_DEPENDS "hector_quadrotor_demo" "hector_quadrotor_gazebo" "panda_description" "panda_gazebo" "panda_control")
set(merge_BUILDTOOL_DEPENDS "catkin")
set(merge_BUILDTOOL_EXPORT_DEPENDS )
set(merge_EXEC_DEPENDS "hector_quadrotor_demo" "hector_quadrotor_gazebo" "panda_description" "panda_gazebo" "panda_control")
set(merge_RUN_DEPENDS "hector_quadrotor_demo" "hector_quadrotor_gazebo" "panda_description" "panda_gazebo" "panda_control")
set(merge_TEST_DEPENDS )
set(merge_DOC_DEPENDS )
set(merge_URL_WEBSITE "")
set(merge_URL_BUGTRACKER "")
set(merge_URL_REPOSITORY "")
set(merge_DEPRECATED "")